### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by thitganuong** [phamleduy04/texas-dps-scheduler#138]
I got new error when run the tool

[07/27/2024 6:40:22] Requesting Available Location....
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1674:34)
    at TLSSocket.emit (node:events:519:28)
    at TLSSocket.emit (node:domain:488:12)
    at TLSSocket._finishInit (node:_tls_wrap:1085:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:871:12) {
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
}

**Comment by PraanavPatel** [comment]
getting same error

**Comment by hari-chintha** [comment]
I'm also getting the same error.

**Comment by AryanPillai2007** [comment]
Getting same error. 
![CleanShot 2024-07-28 at 13 17 20@2x](https://github.com/user-attachments/assets/7cb92b07-f05b-4e6d-b7ac-27e7c47be1c1)

**Comment by nigaonka** [comment]
Same here.. tried running on codespace and local, getting same here.
Appreciate any help

**Comment by phamleduy04** [comment]
![image](https://github.com/user-attachments/assets/94df848a-d4e6-4821-8ca8-14ca0f04c436)

**Comment by yoyoy74662000** [comment]
With this certificate issue, is there anything we have to do?

**Comment by phamleduy04** [comment]
@yoyoy74662000 update the app to the v3.1.0 version by using "git pull" command or simply just delete codespace and create a new one

**Comment by nigaonka** [comment]
First of all, thank you so much for sharing this code and fixing the problem, I am able to run this on my local. 
However, I am getting next error, not sure it's due to local? should it work fine on code space?

 Got 403 status code, retrying...
[07/29/2024 11:59:30] ERROR: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>Microsoft-Azure-Application-Gateway/v2</center>
</body>
</html>







[07/29/2024 11:59:30] WARNING -> Got 403 status code, retrying...
