### ISSUE TITLE
"Miles" is not working

### ISSUE THREAD

**Issue by dradex** [phamleduy04/texas-dps-scheduler#35]
no matter how many miles away I pick it still picks the ones that are ~15-20 away

**Comment by phamleduy04** [comment]
hi, can you provided me your zipcode and which DPS location got picked on your system?

**Comment by sethlee0111** [comment]
I think this is caused by `requestAvailableLocation` returning the original response (`response`), not the filtered one (`filteredResponse`). 

Is there any particular reason that you return the original response at [the code](https://github.com/phamleduy04/texas-dps-scheduler/blob/d1cb3ccbed0f31ea760993bde2ad92f28afe8de0/src/Client/index.ts#L130)?

**Comment by phamleduy04** [comment]
sorry for the late reply, I forgot about this issue 😭. Just push a fix
