### ISSUE TITLE
Won't cancel existing appointment for same-day

### ISSUE THREAD

**Issue by Perksey** [phamleduy04/texas-dps-scheduler#69]
```
[09/15/2023 4:16:06] Carrollton Mega Center is avaliable on 9/15/2023 12:22 PM
[09/15/2023 4:16:08] Slot hold successfully
[09/15/2023 4:16:08] Booking slot....
[09/15/2023 4:16:08] Canceling existing booking 987654321
[09/15/2023 4:16:08] WARNING -> Got 400 status code, retrying...
[09/15/2023 4:16:08] WARNING -> Got 400 status code, retrying...
[09/15/2023 4:16:09] WARNING -> Got 400 status code, retrying...
[09/15/2023 4:16:09] ERROR: Got 400 status code, retrying failed!
```

**Comment by Hotmingy** [comment]
@phamleduy04 when do you think this bug would be fixed ?

**Comment by Perksey** [comment]
I've just looked at cancelling using the website and it looks like old appointments (pre labor day outage) may have a trailing space sent in the first name field. This makes me wonder whether consistency is expected between the appointment holder as reported by the existing booking API and the cancel booking payload.

There's a comment here saying:

https://github.com/phamleduy04/texas-dps-scheduler/blob/a9b9785870b79198b7ca2ac895e911e76648c81a/src/Interfaces/ExistBooking.ts#L8

Perhaps the fields returned by this are indeed pertinent and need to be reused when cancelling the booking?

**Comment by phamleduy04** [comment]
I will take a look at this ASAP

**Comment by phamleduy04** [comment]
Hmm seems like I can't reproduce the error right here

```
[09/18/2023 1:46:00] Texas Scheduler v1.6.5 is starting...
[09/18/2023 1:46:00] Requesting Avaliable Location....
[09/18/2023 1:46:00] WARNING -> You have an existing booking at Denton 10/02/2023 10:00 AM
[09/18/2023 1:46:00] WARNING -> The bot will continue to run, but will cancel existing booking if it found a new one
[09/18/2023 1:46:03] Found 2 avaliable location that match your criteria
[09/18/2023 1:46:03] Lewisville, Carrollton Mega Center
[09/18/2023 1:46:03] Checking Avaliable Location Dates....
--------------------------------------------------------------------------------
[09/18/2023 1:46:03] Lewisville is avaliable on 2/5/2024 9:20 AM
[09/18/2023 1:46:03] Slot hold successfully
[09/18/2023 1:46:03] Booking slot....
[09/18/2023 1:46:03] Canceling existing booking 428285552
[09/18/2023 1:46:04] Canceled booking successfully
[09/18/2023 1:46:09] Slot booked successfully. Confirmation Number: 513128611
[09/18/2023 1:46:09] Visiting this link to print your booking:
[09/18/2023 1:46:09] https://public.txdpsscheduler.com/?b=513128611
```

**Comment by Perksey** [comment]
Can you confirm the contents of the full existing booking response and outbound cancel booking payload? (excluding personal info ofc)

I have a feeling that something changed on the labor day outage that led to the existing bookings no longer matching. My recommendation would be to use data from the existing booking response instead of the local config (as this will be guaranteed to match the appointment)

**Comment by Hotmingy** [comment]
personalInfo:
  # Load from environment secret to prevent personal info leaking
  # If you are using replit free plan, set this true
  # Then add your info to the secrets section
  loadFromEnv: true

  # if loadFromEnv is true, anything in personalInfo beside typeId is ignored
  firstName: ''
  lastName: '
  # Date of birth (08/01/1990)
  dob: '08/01/1990'
  # Use real email to get appointment infomation
  email: ''
  # Not really needed but good to have a real one
  lastFourSSN: ''
  # If you want to recieve notificaion through phone, if not keep blank
  # WARNING: Use number only (Ex: 111111111)
  phoneNumber: ''

  # Serivce you needed at DPS. Check the full list on https://github.com/phamleduy04/texas-dps-scheduler/wiki/TypeId-list
  # If you need to apply for Texas DL you don't need to change it
  typeId: 71

location:
  # Zipcode of your location
  zipCode: '75034'
  # Choose your DPS location by yourself when running the application if set to true
  pickDPSLocation: false
  # Get appointment from all DPS location by distance from the zipcode, will auto skip this when pickDPSLocation is true
  miles: 15
  # Put empty [''] for any day
  # DPS is closed on weekends, so you can't book on Saturday and Sunday
  preferredDays: ['']
  # Put true/false without quotes if you want to book only same day appointment
  sameDay: true
  # Put how many day from today you want to book from start to end (7 is a good number)
  daysAround:
    start: 0
    end: 7
  # Put what time you want to book
  timesAround:
    # Number in 24h format, start = 6 and end = 18 means get appointment between 6 AM - 6 PM
    start: 6
    end: 18

appSettings:
  # Put true/false without quotes if you want to cancel the appointment automatically if found existing appointment
  cancelIfExist: true
  # The time interval (in ms) the app will recheck for newer dates
  interval: 10000
  # Set this to true if you using replit, heroku or something equivalent
  webserver: true
  # Set this to higher if you encounter Header Timeout error. This one is in miliseconds
  headersTimeout: 20000 
  # How many times to retry if the request to DPS server failled
  maxRetry: 3

# If you dont know what to change here, dont change it :)
webhook:
  # If your using Bluebubbles webhook/api put this to true otherwise, keep it false
  enable: false
  url: ''
  password: ''
  # phone number with country code (EX: +11111111111)
  phoneNumber: ''
  # private-api or apple-script
  sendMethod: 'apple-script'
  # iMessage or SMS
  phoneNumberType: 'SMS'


personal info removed, not sure if perhaps I missed a step here.

**Comment by phamleduy04** [comment]
Ok, I found an issue when your local first name has a trailing space it will throw a 400 error.

Error response
```
{"ClassName":"System.Exception","Message":"Unable to cancel booking, booking not found","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at Tx.PublicWebSite.Api.Controller.PublicWebSiteController.CancelBooking(String confirmationNumber, String firstName, String lastName, String dob, String last4Ssn) in D:\\@Source\\Git\\TX DPS\\TxPublicApi\\Tx.PublicWebSite.Api\\Controller\\PublicWebSiteController.cs:line 433\r\n   at Tx.PublicWebSite.Api.Controllers.PublicWebSiteApiController.CancelBooking() in D:\\@Source\\Git\\TX DPS\\TxPublicApi\\Tx.PublicWebSite.Api\\ApiControllers\\PublicWebSiteApiController.cs:line 390","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2146233088,"Source":"Tx.PublicWebSite.Api","WatsonBuckets":null}
```

**Comment by phamleduy04** [comment]
@Hotmingy can you confirm your firstname/lastname on conifg.yml has a trailing space at the end?

**Comment by phamleduy04** [comment]
The existing booking api still accepts the trailing space and returns correct data tho. I will follow @Perksey 's reccomendation

**Comment by Perksey** [comment]
Ah excellent, thanks @phamleduy04!

So my local config never had the trailing space, but when I booked the original appointment through the DPS website I must've accidentally put one in. However, when I logged back into the DPS website I definitely did not do so with a trailing space, but somehow the website knew to add it back in anyway. This leads me to believe that there are omitted fields in the ExistingBooking response that should match exactly when cancelling, but that DPS has some tolerance in the existing booking's name and login name for retrieval purposes. Love the inconsistency! :joy:

**Comment by phamleduy04** [comment]
I pushed some changes, can you guys check if it works?

**Comment by Perksey** [comment]
Will do over the next couple of days, thanks for your help 👍

**Comment by Hotmingy** [comment]
@phamleduy04  Appreciate you help with this. Still same error code :(

**Comment by phamleduy04** [comment]
@Hotmingy did you pull the latest change?

**Comment by phamleduy04** [comment]
If you are using the latest change when the bot shows 400 error it should log the API error response text. Can you share the error? 

fyi if you are using repl.it you can pull latest change just by switching to console mode and type `git pull`. Or easier you can just delete and create a new project again, it should pull the latest update.

**Comment by Hotmingy** [comment]
@phamleduy04 , I will try this now!

**Comment by phamleduy04** [comment]
great! let me know if it works for you. Thank you

**Comment by Hotmingy** [comment]
@phamleduy04 haven't been able to get an appointment at this moment so hard to say if issue still persists. My guess is that it's almost impossible to get same day appointments at this time. Hope to have more luck tomorrow. Thank you for your help

**Comment by Hotmingy** [comment]
@phamleduy04 it works fine now! I just created a new project and was able to get an appointment.
